import React, { useState } from 'react';
import '../styles/Faq.css'; // Custom styles for the FAQ component

const FAQ = () => {
    // This array holds the FAQ data with 9 questions
    const faqData = [
        {
            question: "What is LASK.AI?",
            answer: "LASK.AI is an intelligent code assistant that helps developers by generating, refactoring, and fixing code in real-time."
        },
        {
            question: "How does the code generation feature work?",
            answer: "Our AI analyzes the code context and generates relevant code snippets, suggestions, or even complete functions based on your input."
        },
        {
            question: "Is there support for multiple programming languages?",
            answer: "Yes, LASK.AI supports multiple programming languages including JavaScript, Python, and more."
        },
        {
            question: "What type of code errors can LASK.AI detect?",
            answer: "LASK.AI can detect syntax errors, logical issues, and potential bugs. It can also suggest improvements for code optimization and readability."
        },
        {
            question: "How does LASK.AI integrate with development environments?",
            answer: "LASK.AI integrates seamlessly with popular IDEs like VS Code through extension, providing real-time support during coding sessions."
        },
        {
            question: "Can LASK.AI be customized for my company’s codebase?",
            answer: "Yes, LASK.AI offers customization options to train its AI model on your company’s specific codebase, allowing it to provide more accurate suggestions tailored to your needs.Yes, LASK.AI offers customization options to train its AI model on your company’s specific codebase, allowing it to provide more accurate suggestions tailored to your needs.Yes, LASK.AI offers customization options to train its AI model on your company’s specific codebase, allowing it to provide more accurate suggestions tailored to your needs."
        },
        {
            question: "Is LASK.AI suitable for both junior and experienced developers?",
            answer: "Definitely. LASK.AI is designed to assist developers of all skill levels by providing code suggestions, helping with debugging, and ensuring best coding practices."
        },
        {
            question: "How secure is the code generated by LASK.AI?",
            answer: "LASK.AI ensures that the code it generates adheres to the latest security best practices, reducing the risk of vulnerabilities in your applications."
        }
    ];

    const [activeIndex, setActiveIndex] = useState(null);

    // Toggles the FAQ answer display
    const toggleFAQ = (index) => {
        setActiveIndex(index === activeIndex ? null : index);
    };

    return (
        <section className="faq-section">
            <div className="container">
                <h2 className="faq-title">Frequently Asked Questions</h2>
                <div className="faq-list">
                    {faqData.map((faq, index) => (
                        <div key={index} className="faq-item">
                            <button
                                className="faq-question"
                                onClick={() => toggleFAQ(index)}
                            >
                                {faq.question}
                                <span className={`arrow ${index === activeIndex ? 'up' : 'down'}`}></span>
                            </button>
                            {index === activeIndex && <p className="faq-answer">{faq.answer}</p>}
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default FAQ;
